[server]
url = "http://localhost:8082"

# Solana configuration
[solana]
chain_id = "1001"                 # Solana chain ID
cluster = "devnet"                # devnet, testnet, mainnet-beta
rpc_url = "https://devnet.helius-rpc.com/?api-key=39eae673-f350-4ed8-9e8c-a511ae4f19cf" # Local Solana RPC URL for testing
ws_url = "ws://127.0.0.1:8900"    # Local Solana WebSocket URL for testing

# Solana admin account (deployer/manager)
[solana.admin]
# Base58 encoded private key for Solana devnet testing
private_key = "4LGedYvVgd2LhnPpA5AbZFh8ihcwfzNX3oWrQKHpB8JeQsHFqcE58zgwqfy6jEXqk4fS29BJ3u7hM46oNWxVeF57"
# Base58 encoded public key
public_key = "4rtDRTkYLMUCoCbGyudoLqFm5VovGijLKktT25tgesNm"

# Solana test users
[solana.deployer]
private_key = "23qTr7wk1ag7HYvnSReKYug5mdnJVn4Qyn7a1QYCagJBRYipRjyDfsc9z1jCbvzKZ4GvwBWDENkuYr1NrGzFuHBx"
public_key = "8uGYtsUgU3RnD5mABbbKnnqz8hsq13UjAsboGx3pxBEz"

[solana.creator]
private_key = "55pxM858gTbmdFbkdzD67xsafXk8NFrb6NC5cJcDqWRNsqTef4A2NJx9tEbVDeAAgCQQpCoxEjbn1cM3TxS7VPvd"
public_key = "AzYg48VoM3dm5e5zQYsFdUai1gXLJSG9udsxkUBo5Yqb"

[solana.drds_validator]
private_key = "mRkTPBbdwBPN5KJpJo83FspsELo8SEz4qxoZ2drEm2Lqj6e1c2YEvB1F6Uf6V7pZhHsMFpBrH8uSN9VJbQTfgeo"
public_key = "G3jBX8ZHfM5KLuCScbZiNspczJSpTo8aJ6kwyxyh8W7u"

[solana.user]
private_key = "4KVXzrk5deHzkLFd1caSNHyauCunyx9ZUhvUshkP1r6b3edhgeayFLyZD41RQtd918F3j77zWpUsadrGywsWJmYt"
public_key = "5AXbixRhHhTaaV32zge3U6NVEX2F9LBm3AxV2tspLHXn"

# Solana token addresses (for testing)
[solana.tokens]
# USDC on Solana devnet
usdc = "FFr2L8N6ugjCcViBD7JRECkJvDZPBWj768nF7q7DkFNh"

# Native SOL (wrapped)
wsol = "So11111111111111111111111111111111111111112"
